// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PizzaWebApp.ToppingAPI.Data;

#nullable disable

namespace PizzaWebApp.ToppingAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PizzaWebApp.ToppingAPI.Models.Topping", b =>
                {
                    b.Property<int>("ToppingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ToppingId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ToppingId");

                    b.ToTable("Topping");

                    b.HasData(
                        new
                        {
                            ToppingId = 1,
                            Name = "Tomatoes"
                        },
                        new
                        {
                            ToppingId = 2,
                            Name = "Broccoli"
                        },
                        new
                        {
                            ToppingId = 3,
                            Name = "Red Pepper"
                        },
                        new
                        {
                            ToppingId = 4,
                            Name = "Pepperoni"
                        },
                        new
                        {
                            ToppingId = 5,
                            Name = "Bacon"
                        },
                        new
                        {
                            ToppingId = 6,
                            Name = "Basil"
                        },
                        new
                        {
                            ToppingId = 7,
                            Name = "Mushroom"
                        },
                        new
                        {
                            ToppingId = 8,
                            Name = "Onion"
                        },
                        new
                        {
                            ToppingId = 9,
                            Name = "Extra Cheese"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
